export const BASE_URL = "http://localhost:5000";

export const doctorSpecializations = [
  "General Practice (GP) / Family Medicine",
  "Internal Medicine",
  "Pediatrics",
  "Geriatrics",
  "Cardiology",
  "Endocrinology",
  "Gastroenterology",
  "Hematology",
  "Infectious Disease",
  "Nephrology",
  "Pulmonology",
  "Rheumatology",
  "Neurology",
  "Neurosurgery",
  "Psychiatry",
  "Neuropsychiatry",
  "General Surgery",
  "Cardiothoracic Surgery",
  "Colorectal Surgery",
  "Orthopedic Surgery",
  "Plastic Surgery",
  "Otolaryngology (ENT)",
  "Ophthalmology",
  "Urology",
  "Vascular Surgery",
  "Trauma Surgery",
  "Dentistry",
  "Oral & Maxillofacial Surgery",
  "Orthodontics",
  "Endodontics",
  "Periodontics",
  "Medical Oncology",
  "Radiation Oncology",
  "Surgical Oncology",
  "Pediatric Oncology",
  "Obstetrics",
  "Gynecology",
  "Reproductive Endocrinology",
  "General Pathology",
  "Hematopathology",
  "Forensic Pathology",
  "Cytopathology",
  "Epidemiology",
  "Occupational Medicine",
  "Aerospace Medicine",
  "Sports Medicine",
  "Dermatology",
  "Allergy & Immunology",
  "Ophthalmology",
  "Otolaryngology (ENT)",
  "Physical Medicine & Rehabilitation (PM&R)",
  "Pain Medicine",
  "Chiropractic",
  "Acupuncture & Traditional Chinese Medicine",
  "Genetics & Genomic Medicine",
  "Sleep Medicine",
  "Tropical Medicine",
  "Hyperbaric Medicine",
  "Palliative Care",
  "Transplant Surgery",
  "Geriatric Psychiatry",
  "Interventional Radiology",
  "Nuclear Medicine",
  "Biomedical Engineering & Regenerative Medicine",
];

export const diseaseToSpecialization = {
  "Fungal infection": "Dermatology",
  "Allergy": "Allergy & Immunology",
  "GERD": "Gastroenterology",
  "Chronic cholestasis": "Hepatology",
  "Drug Reaction": "Allergy & Immunology",
  "Peptic ulcer disease": "Gastroenterology",
  "AIDS": "Infectious Disease",
  "Diabetes": "Endocrinology",
  "Gastroenteritis": "Gastroenterology",
  "Bronchial Asthma": "Pulmonology",
  "Hypertension": "Cardiology",
  "Migraine": "Neurology",
  "Cervical spondylosis": "Orthopedic Surgery",
  "Paralysis (brain hemorrhage)": "Neurology",
  "Jaundice": "Hepatology",
  "Malaria": "Infectious Disease",
  "Chicken pox": "Infectious Disease",
  "Dengue": "Infectious Disease",
  "Typhoid": "Infectious Disease",
  "Hepatitis A": "Hepatology",
  "Hepatitis B": "Hepatology",
  "Hepatitis C": "Hepatology",
  "Hepatitis D": "Hepatology",
  "Hepatitis E": "Hepatology",
  "Alcoholic hepatitis": "Hepatology",
  "Tuberculosis": "Pulmonology",
  "Common Cold": "Otolaryngology (ENT)",
  "Pneumonia": "Pulmonology",
  "Dimorphic hemorrhoids (piles)": "Colorectal Surgery",
  "Heart attack": "Cardiology",
  "Varicose veins": "Vascular Surgery",
  "Hypothyroidism": "Endocrinology",
  "Hyperthyroidism": "Endocrinology",
  "Hypoglycemia": "Endocrinology",
  "Osteoarthritis": "Rheumatology",
  "Arthritis": "Rheumatology",
  "(vertigo) Paroxysmal Positional Vertigo": "Otolaryngology (ENT)",
  "Acne": "Dermatology",
  "Urinary tract infection": "Urology",
  "Psoriasis": "Dermatology",
  "Impetigo": "Dermatology"
};


export const doctorQualifications = [
    "MBBS",
    "BMBS",
    "DO",
    "MD",
    "MS",
    "DM",
    "MCh",
    "DNB",
    "FRCS",
    "MRCP",
    "FACP",
    "FCPS",
    "FRCP",
    "PhD (Medical Sciences)",
    "DrPH",
    "DSc (Medicine)",
    "BAMS",
    "BHMS",
    "BUMS",
    "BNYS",
    "BPT",
    "MPT",
    "BSMS",
    "PGDCC",
    "DGO",
    "DCH",
    "DLO",
    "DPM",
    "BDS",
    "MDS",
    "DDS",
    "DMD",
    "BSN",
    "MSN",
    "DNP",
    "PA-C",
    "NP"
  ];
  
  export function capitalizeFirstLetter(string) {
    if (!string) return ""; // Handle empty string case
    return string.charAt(0).toUpperCase() + string.slice(1).toLowerCase();
  };


  export const symptomsData = [
    'itching', 'skin rash', 'nodal skin eruptions', 'continuous sneezing', 'shivering', 
    'chills', 'joint pain', 'stomach pain', 'acidity', 'ulcers on tongue', 'muscle wasting', 
    'vomiting', 'burning micturition', 'spotting urination', 'fatigue', 'weight gain', 
    'anxiety', 'cold hands and feets', 'mood swings', 'weight loss', 'restlessness', 
    'lethargy', 'patches in throat', 'irregular sugar level', 'cough', 'high fever', 
    'sunken eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 
    'yellowish skin', 'dark urine', 'nausea', 'loss of appetite', 'pain behind the eyes', 
    'back pain', 'constipation', 'abdominal pain', 'diarrhoea', 'mild fever', 'yellow urine', 
    'yellowing of eyes', 'acute liver failure', 'fluid overload', 'swelling of stomach', 
    'swelled lymph nodes', 'malaise', 'blurred and distorted vision', 'phlegm', 
    'throat irritation', 'redness of eyes', 'sinus pressure', 'runny nose', 'congestion', 
    'chest pain', 'weakness in limbs', 'fast heart rate', 'pain during bowel movements', 
    'pain in anal region', 'bloody stool', 'irritation in anus', 'neck pain', 'dizziness', 
    'cramps', 'bruising', 'obesity', 'swollen legs', 'swollen blood vessels', 
    'puffy face and eyes', 'enlarged thyroid', 'brittle nails', 'swollen extremities', 
    'excessive hunger', 'extra marital contacts', 'drying and tingling lips', 
    'slurred speech', 'knee pain', 'hip joint pain', 'muscle weakness', 'stiff neck', 
    'swelling joints', 'movement stiffness', 'spinning movements', 'loss of balance', 
    'unsteadiness', 'weakness of one body side', 'loss of smell', 'bladder discomfort', 
    'foul smell of urine', 'continuous feel of urine', 'passage of gases', 'internal itching', 
    'toxic look (typhos)', 'depression', 'irritability', 'muscle pain', 'altered sensorium', 
    'red spots over body', 'belly pain', 'abnormal menstruation', 'dischromic patches', 
    'watering from eyes', 'increased appetite', 'polyuria', 'family history', 'mucoid sputum', 
    'rusty sputum', 'lack of concentration', 'visual disturbances', 'receiving blood transfusion', 
    'receiving unsterile injections', 'coma', 'stomach bleeding', 'distention of abdomen', 
    'history of alcohol consumption', 'blood in sputum', 
    'prominent veins on calf', 'palpitations', 'painful walking', 'pus filled pimples', 
    'blackheads', 'scurring', 'skin peeling', 'silver like dusting', 'small dents in nails', 
    'inflammatory nails', 'blister', 'red sore around nose', 'yellow crust ooze', 'prognosis'
]
