export const BASE_URL = "http://localhost:5000";

export const doctorSpecializations = [
  "General Practice (GP) / Family Medicine",
  "Internal Medicine",
  "Pediatrics",
  "Geriatrics",
  "Cardiology",
  "Endocrinology",
  "Gastroenterology",
  "Hematology",
  "Infectious Disease",
  "Nephrology",
  "Pulmonology",
  "Rheumatology",
  "Neurology",
  "Neurosurgery",
  "Psychiatry",
  "Neuropsychiatry",
  "General Surgery",
  "Cardiothoracic Surgery",
  "Colorectal Surgery",
  "Orthopedic Surgery",
  "Plastic Surgery",
  "Otolaryngology (ENT)",
  "Ophthalmology",
  "Urology",
  "Vascular Surgery",
  "Trauma Surgery",
  "Dentistry",
  "Oral & Maxillofacial Surgery",
  "Orthodontics",
  "Endodontics",
  "Periodontics",
  "Medical Oncology",
  "Radiation Oncology",
  "Surgical Oncology",
  "Pediatric Oncology",
  "Obstetrics",
  "Gynecology",
  "Reproductive Endocrinology",
  "General Pathology",
  "Hematopathology",
  "Forensic Pathology",
  "Cytopathology",
  "Epidemiology",
  "Occupational Medicine",
  "Aerospace Medicine",
  "Sports Medicine",
  "Dermatology",
  "Allergy & Immunology",
  "Ophthalmology",
  "Otolaryngology (ENT)",
  "Physical Medicine & Rehabilitation (PM&R)",
  "Pain Medicine",
  "Chiropractic",
  "Acupuncture & Traditional Chinese Medicine",
  "Genetics & Genomic Medicine",
  "Sleep Medicine",
  "Tropical Medicine",
  "Hyperbaric Medicine",
  "Palliative Care",
  "Transplant Surgery",
  "Geriatric Psychiatry",
  "Interventional Radiology",
  "Nuclear Medicine",
  "Biomedical Engineering & Regenerative Medicine",
];


export const doctorQualifications = [
    "MBBS",
    "BMBS",
    "DO",
    "MD",
    "MS",
    "DM",
    "MCh",
    "DNB",
    "FRCS",
    "MRCP",
    "FACP",
    "FCPS",
    "FRCP",
    "PhD (Medical Sciences)",
    "DrPH",
    "DSc (Medicine)",
    "BAMS",
    "BHMS",
    "BUMS",
    "BNYS",
    "BPT",
    "MPT",
    "BSMS",
    "PGDCC",
    "DGO",
    "DCH",
    "DLO",
    "DPM",
    "BDS",
    "MDS",
    "DDS",
    "DMD",
    "BSN",
    "MSN",
    "DNP",
    "PA-C",
    "NP"
  ];
  
  